### ISSUE TITLE
Split dependencies from project files during build

### ISSUE THREAD

**Issue by jourdanrodrigues** [WLSF/microservices#3]
That's an approach to gain time at development. Here it is:

```dockerfile
# From this
ADD . /blog-reply
RUN pip install -r /blog-reply/requirements.txt
# To this
COPY ./requirements.txt /blog-reply
RUN pip install -r /blog-reply/requirements.txt
COPY . /blog-reply
```

That can also be solved via volumes, which makes the build much more lightweight:

```yml
services:
  ...
  blog-reply:
    ...
    volumes:
      - ./blog-reply:/blog-reply
```

Uniting those can be crucially beneficial to development sanity, though it's an overkill if not using Docker to develop.
